repos:
  - repo: https://github.com/bwhmather/ssort
    rev: v0.11.6
    hooks:
      - id: ssort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [ --profile=black ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [ --strict , --ignore-missing-imports, --no-namespace-packages ]
        additional_dependencies:
          - pydantic
          - pytest
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.128
    hooks:
      - id: ruff
        args: [ --fix ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --line-length=88
          - --include='\.pyi?$'
